### ISSUE TITLE
PDF export for course modules fail

### ISSUE THREAD

**Issue by windowz414** [ucoruh/course-note-template#4]
I get these outputs during the generation;
```
miktex-dvipdfmx: major issue: So far, you have not checked for MiKTeX updates.
xelatex: major issue: So far, you have not checked for MiKTeX updates.
miktex-dvipdfmx: major issue: So far, you have not checked for MiKTeX updates.
xelatex: major issue: So far, you have not checked for MiKTeX updates.
miktex-dvipdfmx: major issue: So far, you have not checked for MiKTeX updates.
xelatex: major issue: So far, you have not checked for MiKTeX updates.
[WARNING] Missing character: There is no τî½ (U+732B) in font [lmroman10-regular]:mapping=tex-text;!
```

Happens on both English and Turkish variants. I'll push my changes to my fork soon.

**Comment by ucoruh** [comment]
in markdown when we copy it. The copied items have unsupported encoding if we edit them manually. These problems are solved. We have to check the special characters that cause this issue. Others are related to versions that we have to update.

**Comment by windowz414** [comment]
> in markdown when we copy it. The copied items have unsupported encoding if we edit them manually. These problems are solved. We have to check the special characters that cause this issue. Others are related to versions that we have to update.

Alrighty, thanks a lot! That also seems to be a generic issue with MiKTeX on Windows as it doesn't happen on Linux when I run a local script I converted from your Windows script.
